### ISSUE TITLE
Kaifa måler - ingen energimåling etter 100000 kwh

### ISSUE THREAD

**Issue by Ugo-dot** [Csstenersen/node-red-contrib-ams-decoder#1]
Hei,
har brukt denne noden i ett år på en Kaifa måler og den har fungert supert. For noen uker siden så jeg at det ikke kom inn energmålerverdi lenger. Effektmålingen kommer, men den har sporadiske feil. Mangler A på L1 og, spenningsverdiene er feil.
Har ikke funnet ut av årsaken, men nå gikk det opp for meg at måleren har rundet 100000kWh timer. 
Kan det være en bug i forbindelse med dette?

Får denne feilmeldingen: "Data is not compatible, Check string from AMS-meter"

**Comment by Csstenersen** [comment]
Kan du logge data før noden og sende til meg?

**Comment by Ugo-dot** [comment]
Hei, er denne til hjelp?
[kaifa debug.txt](https://github.com/Csstenersen/node-red-contrib-ams-decoder/files/6299911/kaifa.debug.txt)

**Comment by Csstenersen** [comment]
> Hei, er denne til hjelp?
> [kaifa debug.txt](https://github.com/Csstenersen/node-red-contrib-ams-decoder/files/6299911/kaifa.debug.txt)

Takk!
hmm. Det ser ut til at dataene som kommer inn i AMS dekoderen er inkonsekvendte. De burde være like i antall tegn hvert 2sekund, 10sekund og 3600sekund iht. spesifikajsonen til kaifa: https://www.nek.no/wp-content/uploads/2018/11/Kaifa-KFM_001.pdf

Jeg foreslår at du evt prøver å gjøre noen endringer i innstillinger på den serielle noden eller evt. prøve et annet serielt grensesnitt for å se om dataene blir konsekvendte i lengden?

**Comment by Ugo-dot** [comment]
Har prøvd litt forskjellige innstillinger på seriell noden uten at jeg har funnet noe som fungerer. Det jeg har brukt frem til nå er "a silence of" 1500ms.
Bruker en mbus - ttl omformer. Byttet denne til en ny (samme type), uten bedring. Begynner å lure på om det er feil på selve måleren?

**Comment by Csstenersen** [comment]
Hmm det er jo noe slik jeg også har innstilt på den noden.
Hvis det hadde vært feil på måleren så ville jeg kanskje tro at du fikk feil data inn i elhub også? ser verdiene der riktig ut? 
https://plugin.elhub.no/

Jeg hadde nok forsøkt å skifte den USB til ttl å se om verdiene endrer struktur eller om de forblir like.

**Comment by Ugo-dot** [comment]
Verdiene fra elhub ser fornuftige ut. 
Det er en mbus til ttl jeg bruker. Har byttet denne. Har ingen usb interface tilgjengelig. Kan prøve en annen RPi når jeg får anledning.

**Comment by Ugo-dot** [comment]
Liten oppdatering. I helga så jeg at verdiene plutselig begynte å  komme inn mer normalt, uten at jeg hadde gjort noe. 
Her i går sjekket jeg litt da det kom inn noen veldig høye effekt verdier. Da ser jeg at paritet på seriell noden er satt til none. Husker jeg måtte bruke none, og ikke even når jeg satte den opp første gang, for å få inn verdier. Satte den tilbake til even, og nå ser det veldig bra ut. Legger ved ny logg. Ser at lengden er mer konsekvent, selv om jeg ikke blir helt klok på den. Lukker issuen da ingenting tyder på at det er noe feil med noden. Takk for hjelp, og for at du har lagd noden :-)
[kaifa debug2.txt](https://github.com/Csstenersen/node-red-contrib-ams-decoder/files/6353565/kaifa.debug2.txt)

**Comment by Ugo-dot** [comment]
Var litt snar der... ser at nå er det masse rare verdier igjen.

**Comment by Ugo-dot** [comment]
Liten oppdatering. Fikk tak i et mbus til usb grensesnitt, og byttet til dette. Nå ser verdiene mye bedre ut  :-). Problemet ser altså ut til å være i forbindelse med mbus til ttl converteren.
