### ISSUE TITLE
Power consumption

### ISSUE THREAD

**Issue by hesmebye** [Csstenersen/node-red-contrib-ams-decoder#2]
Thanks for a great component!

I am living in Oslo and have connected the HAN port on our aidon smart meeter with node red with your ams decoder.
Everything seems to work fine, except that I can not find the accumulated power consumption.
In the documentation for the meeter, the accumulated power is described as a output.
It this supported?

**Comment by Csstenersen** [comment]
Hi and thanks for the support!
The HAN-port does output the accummulated energy consumption once every whole as the meter stand/value. 

To find consumption for the previous hour you have to take the new meter value minus the old meter value.

the way i do it, is to store the values in a database (influx) and query the difference pr hour to get the energy consumption. I use grafana to query and visualise this.

hope this helps!

**Comment by hesmebye** [comment]
Thanks - got it on track now :)
